version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install aws-sdk 
      - npm install winston winston-cloudwatch
  build:
    commands:
      # - echo "Zipping deployment package..."
      # - cd node_modules
      # - zip -r9 ../deployment_package.zip .
      # - cd ..
      #- zip -g deployment_package.zip index.js
      - zip  deployment_package.zip index.js logger.js package.js package-lock.json
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name Serverless-api --zip-file fileb://deployment_package.zip
      - echo "success!"